kappa: -1
R_tach: 0.25
R_imu: 0.25
R_gnss: [0.0001, 0
        0, 0.0001]

process_noise_covariance_Q: [1, 0, 0, 0,
                             0, 1, 0, 0,
                             0, 0, 0.5, 0,
                             0, 0, 0, 0.15]

initial_estimate_covariance_P: [1e-3, 0, 0, 0,
                                0, 1e-3, 0, 0,
                                0, 0, 0.1, 0,
                                0, 0, 0, 0.7]
