kappa: -2
R_tach: 0.25
R_imu: 0.0025
R_gnss: [0.0001, 0,
        0, 0.0001]

process_noise_covariance_Q: [2.514, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 64.6, 0.0, 0.0,
                            0.0, 0.0, 0.0, 9.418, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.5]

initial_estimate_covariance_P: [0.006356, 0.0, 0.0, 0.0, 0.0,
                                0.0, 0.0005098, 0.0, 0.0, 0.0,
                                0.0, 0.0, 0.2484, 0.0, 0.0,
                                0.0, 0.0, 0.0, 0.1859, 0.0,
                                0.0, 0.0, 0.0, 0.0, 5.593e-05]
